name = "SimplePadic"
uuid = "ace0dc1f-4b04-4dd6-8036-baf16b2183e6"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.0"

[deps]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[compat]
julia = "1"
Nemo = "0.25, 0.26"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]