name = "SimplePadics"
uuid = "2edc7d5a-420c-455a-9f50-96c88fa4f765"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.3"

[deps]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[compat]
julia = "1"
Nemo = "0.25, 0.26"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]